apiVersion: v1
kind: Secret
metadata:
  name: iomt-healthcare-secret
  labels:
    app: iomt-healthcare
type: Opaque
data:
  # Base64 encoded value of "iomt-cloud-security-secret-key-12345#"
  JWT_SECRET: aW9tdC1jbG91ZC1zZWN1cml0eS1zZWNyZXQta2V5LTEyMzQ1Iw==
